### ISSUE TITLE
Odd Results of Joint Version on Nuscenes

### ISSUE THREAD

**Issue by Longzhong-Lin** [roggirg/AutoBots#6]
Hi there. I've tried the instructions in README to train a joint version Autobots on  dataset Nuscenes, but I found the metrics on "val" part go up during training. I'm wondering is this a normal phenomenon? The picture is the corresponding results.
![image](https://user-images.githubusercontent.com/81036197/177019713-e957a4ec-8816-436b-a200-c69aae2566ed.png)

**Comment by roggirg** [comment]
Hi,

Sorry for the delay. 
Yes this seems like normal behavior on the nuScenes for joint prediction. The problem is there is a lot of missing agent data (e.g., incomplete trajectories) so I think it tends to overfit as it memorizes the scenes. The nuScenes dataset was not designed for joint prediction. This is why we provide experiments on the interaction-dataset which was designed multi-agent trajectory prediction.

Thanks,

**Comment by Longzhong-Lin** [comment]
Got it! Thanks for the explanation.
